### PR TITLE
5 add dockerfile to easy deploy website

### LINKED ISSUE #5: Add dockerfile to easy deploy website
To share this project with other orchestra, the deployement step shall be an easy one.

A first step to this shall be to create a docker file to instantiate an instance of the website easily.

### PR DESCRIPTION
**Pull request by ofaurax**
Fix #5

### CODE REVIEW

**Comment by kimicol** [comment]
I get the following error when running docker image :
```
$ docker run --name arvin2 --network host -it arvin2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.65.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.65.3. Set the 'ServerName' directive globally to suppress this message
```
The webpage is not available at `http://localhost:1912`.
I quickly searched on internet a way to fix it but nothing worked.

Running on :
- Windows 11
- WSL 2, Ubuntu
- Docker 4.28.0

**Comment by kimicol** [comment]
Complete output of docker running :
```
$ docker run --rm --name arvin2 --network host -it arvin2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.65.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.65.3. Set the 'ServerName' directive globally to suppress this message
[Sat Apr 27 14:32:25.284401 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/7.4.33 configured -- resuming normal operations
[Sat Apr 27 14:32:25.284441 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Output in firefox :
image

**Comment by ofaurax** [comment]
Did you try to access `http://192.168.65.3:1912` ?

**Comment by ofaurax** [comment]
Do you try to access it from windows or Ubuntu? It should be accessible from the host OS running docker

**Comment by kimicol** [comment]
> Did you try to access `http://192.168.65.3:1912` ?

Yes, didn't work either.

> Do you try to access it from windows or Ubuntu? It should be accessible from the host OS running docker

It works on my Debian computer, I've just tried it.

The problem should come from my windows laptop which I tried first. Maybe there is an error with WSL. I will search deeper on my configuration but it shouldn't imply to modify the Dockerfile. However maybe the commands given in README.md shall be adapted.

**Pull request merged**
